import 'package:stronger/models/enums.dart';
import 'package:stronger/models/exercise.dart';

final List<Exercise> defaultExercisesList = [
  Exercise(
    id: 'default_bench_press',
    name: 'Barbell Bench Press',
    description: 'Lie on a flat bench, grip the barbell slightly wider than shoulder-width, lower it to your chest, and push back up.',
    primaryMuscleGroup: MuscleGroup.chest,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.barbell,
    recommendedReps: 8,
    notes: 'Keep your feet flat on the floor and maintain a controlled descent.',
  ),
  Exercise(
    id: 'default_squat',
    name: 'Barbell Back Squat',
    description: 'Rest the barbell on your upper back, drop your hips down until your thighs are parallel to the ground, then drive back upwards.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.barbell,
    recommendedReps: 6,
    notes: 'Keep your core braced and do not let your knees collapse inward.',
  ),
  Exercise(
    id: 'default_pullup',
    name: 'Pull-Up',
    description: 'Hang from a pull-up bar with palms facing away from you, pull your body upwards until your chin clears the bar.',
    primaryMuscleGroup: MuscleGroup.back,
    difficulty: Difficulty.advanced,
    equipment: Equipment.bodyweight,
    recommendedReps: 10,
    notes: 'Engage your shoulder blades before initiating the pull.',
  ),
  Exercise(
    id: 'default_pushup',
    name: 'Push-Up',
    description: 'Standard floor push-up tracking from a plank position down to the chest level.',
    primaryMuscleGroup: MuscleGroup.chest,
    difficulty: Difficulty.beginner,
    equipment: Equipment.bodyweight,
    recommendedReps: 15,
    notes: 'Maintain a straight line from head to heels.',
  ),
  Exercise(
    id: 'default_bicep_curl',
    name: 'Dumbbell Bicep Curl',
    description: 'Stand tall holding dumbbells at your side, flex at the elbows turning palms upward, and squeeze the biceps.',
    primaryMuscleGroup: MuscleGroup.arms,
    difficulty: Difficulty.beginner,
    equipment: Equipment.dumbbell,
    recommendedReps: 12,
    notes: 'Avoid swinging your upper body to gain momentum.',
  ),
  Exercise(
    id: 'default_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    description: 'Sit or stand holding dumbbells at shoulder level, press the weights directly overhead until your arms are locked.',
    primaryMuscleGroup: MuscleGroup.shoulders,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.dumbbell,
    recommendedReps: 10,
    notes: 'Control the weights on the way down to ear level.',
  ),
  Exercise(
    id: 'default_leg_press',
    name: 'Machine Leg Press',
    description: 'Sit in the machine sled, place feet shoulder-width apart on the sled platform, lower the weight to 90 degrees and push.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.beginner,
    equipment: Equipment.machine,
    recommendedReps: 12,
    notes: 'Do not lock your knees completely out at the top.',
  ),
  Exercise(
    id: 'default_lat_pulldown',
    name: 'Cable Lat Pulldown',
    description: 'Sit at a pulldown station, pull the wide bar down smoothly towards your upper chest area.',
    primaryMuscleGroup: MuscleGroup.back,
    difficulty: Difficulty.beginner,
    equipment: Equipment.cable,
    recommendedReps: 10,
    notes: 'Focus on pulling with your elbows rather than your hands.',
  ),
  Exercise(
    id: 'default_deadlift',
    name: 'Barbell Deadlift',
    description: 'Stand with feet mid-foot under the barbell, bend over and grab the bar, lift the bar by extending your hips and knees.',
    primaryMuscleGroup: MuscleGroup.back,
    difficulty: Difficulty.advanced,
    equipment: Equipment.barbell,
    recommendedReps: 5,
    notes: 'Keep your spine neutral and the bar close to your body.',
  ),
  Exercise(
    id: 'default_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    description: 'Stand holding dumbbells, raise your arms to the sides until they are parallel to the floor, then lower them slowly.',
    primaryMuscleGroup: MuscleGroup.shoulders,
    difficulty: Difficulty.beginner,
    equipment: Equipment.dumbbell,
    recommendedReps: 15,
    notes: 'Keep a slight bend in your elbows and lead with your elbows.',
  ),
  Exercise(
    id: 'default_triceps_pushdown',
    name: 'Cable Triceps Pushdown',
    description: 'Hold the cable attachment at chest level, push down by extending your elbows, and return slowly.',
    primaryMuscleGroup: MuscleGroup.arms,
    difficulty: Difficulty.beginner,
    equipment: Equipment.cable,
    recommendedReps: 12,
    notes: 'Keep your elbows tucked into your sides and do not flare them.',
  ),
  Exercise(
    id: 'default_plank',
    name: 'Plank',
    description: 'Hold a push-up position but rest your weight on your forearms rather than your hands. Keep your body straight.',
    primaryMuscleGroup: MuscleGroup.core,
    difficulty: Difficulty.beginner,
    equipment: Equipment.bodyweight,
    recommendedReps: 60,
    notes: 'Hold for time (seconds). Squeeze your glutes and brace your core.',
  ),
  Exercise(
    id: 'default_leg_raise',
    name: 'Hanging Leg Raise',
    description: 'Hang from a bar, lift your legs to a 90-degree angle keeping them straight, and lower them slowly.',
    primaryMuscleGroup: MuscleGroup.core,
    difficulty: Difficulty.advanced,
    equipment: Equipment.bodyweight,
    recommendedReps: 10,
    notes: 'Avoid swinging; use your lower abs to initiate the movement.',
  ),
  Exercise(
    id: 'default_incline_press',
    name: 'Incline Dumbbell Press',
    description: 'Lie on an incline bench, hold dumbbells at shoulder width, and press them up until arms are fully extended.',
    primaryMuscleGroup: MuscleGroup.chest,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.dumbbell,
    recommendedReps: 10,
    notes: 'Focus on the upper chest. Angle the bench around 30-45 degrees.',
  ),
  Exercise(
    id: 'default_lunge',
    name: 'Dumbbell Lunge',
    description: 'Step forward with one leg, lowering your hips until both knees are bent at about 90 degrees, then push back up.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.beginner,
    equipment: Equipment.dumbbell,
    recommendedReps: 12,
    notes: 'Keep your front knee aligned over your ankle.',
  ),
  Exercise(
    id: 'default_calf_raise',
    name: 'Standing Calf Raise',
    description: 'Stand on a calf raise machine platform, lower your heels as far as possible, then push up onto your toes.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.beginner,
    equipment: Equipment.machine,
    recommendedReps: 15,
    notes: 'Hold the contraction at the top for a second.',
  ),
  Exercise(
    id: 'default_hammer_curl',
    name: 'Dumbbell Hammer Curl',
    description: 'Stand holding dumbbells with a neutral grip (palms facing each other), flex at the elbows, and squeeze.',
    primaryMuscleGroup: MuscleGroup.arms,
    difficulty: Difficulty.beginner,
    equipment: Equipment.dumbbell,
    recommendedReps: 12,
    notes: 'Targets the brachialis and forearm muscles.',
  ),
  Exercise(
    id: 'default_tricep_extension',
    name: 'Overhead Dumbbell Extension',
    description: 'Sit and hold a single dumbbell overhead with both hands, lower it behind your head, then extend your elbows.',
    primaryMuscleGroup: MuscleGroup.arms,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.dumbbell,
    recommendedReps: 10,
    notes: 'Keep your elbows pointing forward, not flared out.',
  ),
  Exercise(
    id: 'default_barbell_row',
    name: 'Bent-Over Barbell Row',
    description: 'Hinge forward at the hips, hold the barbell with a shoulder-width grip, and pull it to your lower chest/navel.',
    primaryMuscleGroup: MuscleGroup.back,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.barbell,
    recommendedReps: 8,
    notes: 'Keep your back flat and pull through your elbows.',
  ),
  Exercise(
    id: 'default_romanian_deadlift',
    name: 'Barbell Romanian Deadlift',
    description: 'Hold a barbell, hinge at your hips keeping legs relatively straight with a slight bend, lower the bar, then stand up.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.barbell,
    recommendedReps: 10,
    notes: 'Focus on feeling a stretch in your hamstrings and squeeze your glutes at the top.',
  ),
  Exercise(
    id: 'default_face_pull',
    name: 'Cable Face Pull',
    description: 'Pull the rope attachment towards your face, flaring your elbows and rotating your hands outward.',
    primaryMuscleGroup: MuscleGroup.shoulders,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.cable,
    recommendedReps: 15,
    notes: 'Great for rear delts and rotator cuffs. Keep it controlled.',
  ),
  Exercise(
    id: 'default_cable_crossover',
    name: 'Cable Crossover',
    description: 'Stand between pulley stations, grab handles, lean slightly forward, and pull cables together in an arc.',
    primaryMuscleGroup: MuscleGroup.chest,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.cable,
    recommendedReps: 12,
    notes: 'Focus on squeezing the chest muscles at the center.',
  ),
  Exercise(
    id: 'default_russian_twist',
    name: 'Russian Twist',
    description: 'Sit on the floor, lean back slightly, elevate your feet, and twist your torso side to side.',
    primaryMuscleGroup: MuscleGroup.core,
    difficulty: Difficulty.beginner,
    equipment: Equipment.bodyweight,
    recommendedReps: 20,
    notes: 'You can hold a weight block or medicine ball to increase difficulty.',
  ),
  Exercise(
    id: 'default_chinup',
    name: 'Chin-Up',
    description: 'Hang from a bar with palms facing towards you, pull yourself up until chin clears the bar.',
    primaryMuscleGroup: MuscleGroup.arms,
    difficulty: Difficulty.intermediate,
    equipment: Equipment.bodyweight,
    recommendedReps: 8,
    notes: 'Engages the biceps more than a regular pull-up.',
  ),
  Exercise(
    id: 'default_leg_curl',
    name: 'Lying Leg Curl Machine',
    description: 'Lie face down on the machine, place rollers on back of calves, and flex your knees to pull the weight in.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.beginner,
    equipment: Equipment.machine,
    recommendedReps: 12,
    notes: 'Control the release back to the starting position.',
  ),
  Exercise(
    id: 'default_leg_extension',
    name: 'Machine Leg Extension',
    description: 'Sit in the extension machine, place shins behind pad, and extend your knees to raise the weight.',
    primaryMuscleGroup: MuscleGroup.legs,
    difficulty: Difficulty.beginner,
    equipment: Equipment.machine,
    recommendedReps: 12,
    notes: 'Squeeze the quads at the top peak contraction.',
  ),
];
